version: '3.8'

services:
  api:
    build: ./API
    ports:
      - "3000:3000"
    volumes:
      - ./API:/app
    environment:
      - NODE_ENV=development
    # Removido: depends_on

  frontend:
    build: ./Front_end
    ports:
      - "8080:80"
