name: Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build e Push da API
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-imc ./API
          docker push ${{ secrets.DOCKER_USERNAME }}/api-imc

      - name: Build e Push do Front-end
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/front-end-app-imc ./Front_end
          docker push ${{ secrets.DOCKER_USERNAME }}/front-end-app-imc